### ISSUE TITLE
question

### ISSUE THREAD

**Issue by gaosir123** [TomStog/Infrared-SpO2#6]
Hello, I still have some questions. The 19 seconds in your video are divided equally. Are the blood oxygen saturation values ​​​​the same in these 19 seconds? If they are not the same value, how to deal with it?

**Comment by TomStog** [comment]
Of course SpO2 fluctuates but we made some assumptions in order to calculate it. One assumption was that the real SpO2 value was the value shown by the finger pulse oximeter. Another assumption was that the SpO2 doesn't fluctuate within our time window. Of course, the narrower the time window, the more accurate the prediction.

**Comment by gaosir123** [comment]
If the videos used are of different lengths, will it affect the experiment?

**Comment by TomStog** [comment]
I don't know, different video lengths would mean different number of samples per training/testing. It feels like training a CNN on different size images. Can you give me an example of how different these video lengths are ?

**Comment by gaosir123** [comment]
Then I would like to ask if your video is directly amplified by EVM and then extracted features, or does it need to be denoised and other operations?

**Comment by TomStog** [comment]
First, we apply motion attenuation and then motion magnification and feature extraction. There isn't any denoising step involved.

**Comment by gaosir123** [comment]
How motion attenuation is achieved？

**Comment by TomStog** [comment]
I've uploaded the MATLAB code.You can find all the functions needed here:
https://github.com/rgov/vidmag

**Comment by gaosir123** [comment]
Hello, now I have some problems with Average RMSE, Minimum RMSE, MAE, MAPE, 𝑹𝟐 score and No. Features output. Do you have any code in this regard?
In addition, I want to know whether this model can be called to predict the SpO2 value of new data after the regressor runs successfully.
