### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by gaosir123** [TomStog/Infrared-SpO2#7]
Hello, now I have some problems with Average RMSE, Minimum RMSE, MAE, MAPE, 𝑹𝟐 score and No. Features output. Do you have any code in this regard?
In addition, I want to know whether this model can be called to predict the SpO2 value of new data after the regressor runs successfully.

**Comment by TomStog** [comment]
If you can share what kind of problems, then I might be able to provide you with better advice and help.

Yes, if you save the model after training, then you can call it whenever you have new data for predicting the SpO2.

**Comment by gaosir123** [comment]
`average_rmse = math.sqrt(mean_squared_error(mse_total, [mean(mse_total)] * len(mse_total)))
minimum_rmse = math.sqrt(min(mse_total))
mae = mean(mae_total)
mape = mean_absolute_error(mse_total, [mean(mse_total)] * len(mse_total)) * 100 / mean(mse_total)
y_mean = mean(mse_total)
ss_total = sum((y - y_mean) ** 2 for y in mse_total)
ss_residual = sum((y - y_hat) ** 2 for y, y_hat in zip(mse_total, [y_mean] * len(mse_total)))
r2 = 1 - (ss_residual / ss_total)

print("Average RMSE: %.3f" % average_rmse)
print("Minimum RMSE: %.3f" % minimum_rmse)
print("MAE: %.3f" % mae)
print("MAPE: %.3f%%" % mape)
print("R² Score: %.3f" % r2)
print("No. Features: %d" % len(Z[0]))

dump(model, 'D:\\模型\\完整数据模型\\ETR1\\model.joblib')`
In order to output the desired data, I added the above code after the regressor code. But I found that the output results were wrong.

**Comment by gaosir123** [comment]
And when there is a large amount of data in the csv file, the following error result will appear.
No data points available.
Traceback (most recent call last):
File "E:/虚拟环境/实验大全/ETR.py", line 123, in <module>
print(Z[0])
IndexError: list index out of range

Process finished with exit code 1

**Comment by gaosir123** [comment]
The most important thing is that I don't quite understand how to save the model and how to call the model later.

**Comment by gaosir123** [comment]
The output that I think is mainly wrong is the R² Score. Because it is always 0.

**Comment by TomStog** [comment]
I suggest you take a look at Python's sklearn metrics website : https://scikit-learn.org/stable/modules/model_evaluation.html
There's no need to calculate those metrics "by hand" when you can import "ready-to-use" functions.

You absolutely can save a neural net model to your local disk and call the model to perform predictions. I suggest you take a look at this article : https://machinelearningmastery.com/save-load-keras-deep-learning-models/

ISO 80601-2-61:2019 standard states that the root mean square accuracy, which represents the deviation of the measurement from the true value, must not exceed 2% of the SpO2 range. So you don't need to worry about R2 score.

**Comment by gaosir123** [comment]
I read the article you provided me and modified the code, but I think there is still a problem with the output value. It feels like the code is wrong.
`# Linear Regression Algorithms
from sklearn.linear_model import LinearRegression, Ridge, SGDRegressor, ElasticNet, Lasso, Lars, Lasso, LassoLars, \
    HuberRegressor, QuantileRegressor, RANSACRegressor, TheilSenRegressor, PoissonRegressor, TweedieRegressor, \
    GammaRegressor

# Non-linear Regression Algorithms
from sklearn.ensemble import AdaBoostRegressor, BaggingRegressor, ExtraTreesRegressor, GradientBoostingRegressor, \
    RandomForestRegressor, StackingRegressor, VotingRegressor, HistGradientBoostingRegressor

from sklearn.tree import DecisionTreeRegressor

import pandas as pd
from pandas import read_csv
from sklearn.metrics import mean_absolute_error, max_error, median_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from keras.models import load_model
import numpy as np
from numpy import mean, median
from sklearn.model_selection import KFold
# import matplotlib.pyplot as plt
import warnings

from itertools import chain, combinations


# "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"

def powerset(iterable):
    s = list(iterable)  # allows duplicate elements
    return chain.from_iterable(combinations(s, r) for r in range(len(s) + 1))


if __name__ == "__main__":

    combo_arr = []
    stuff = ['var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8', 'var_9', 'var_10', 'var_11',
             'var_12']
    for i, combo in enumerate(powerset(stuff), 1):
        combo_arr.append(combo)

    my_combo = combo_arr[(len(stuff) + 1):]
    # print(my_combo)

    """LOAD DATA"""

    # Read data from CSV file
    data = pd.read_csv(r'./filename_12vars_3rd_group_mag - 副本.csv')
    warnings.filterwarnings("ignore")
    # Define y = f(x)
    predictors_list = np.array(my_combo)
    outcome = ['SpO2']

    # Normalization Parameter
    norm_param = 100

    # Define kfold cross validation
    kf = KFold(n_splits=5, random_state=None, shuffle=True)

    """SPLIT AND PREDICT"""

    mae_total = []
    mse_total = []
    mse_list = []
    rmse_list = []
    mae_list = []
    mape_list = []
    r2_list = []
    for predictors in predictors_list:
        X = data[np.array(predictors)].values
        y = data[outcome]

        X = np.array(X)
        y = np.array(y)
        mae_20 = []
        mse_20 = []
        mse_20 = []
        rmse_20 = []
        mape_20 = []
        r2_20 = []
        for i in range(20):
            mae = []
            mse = []
            for train_index, test_index in kf.split(X, y):
                # Split the data
                X_train, X_test = X[train_index], X[test_index]
                y_train, y_test = y[train_index] / norm_param, y[test_index] / norm_param

                # Insert Regression Algorithm
                # base_estimator=DecisionTreeRegressor(max_depth=10)
                model = ExtraTreesRegressor(n_estimators=100, random_state=None)
                model.fit(X_train, y_train)

                # Predict with X_test
                y_hat = model.predict(X_test)
                y_hat = y_hat.reshape(len(y_hat), 1)

                bool_mae = np.isnan(mean_absolute_error(y_test, y_hat))
                bool_mse = np.isnan(mean_squared_error(y_test, y_hat))

                # Calculate the metric
                if bool_mae or bool_mse:
                    continue
                else:
                    mae.append(mean_absolute_error(y_test, y_hat))
                    mse.append(mean_squared_error(y_test, y_hat))

            if (all(x <= ((2 / norm_param) ** 2) for x in mse)):
                mse_20.append(mean(mse))
                rmse_20.append(mean(mse) ** 0.5)
                mae_20.append(mean(mae))
                mape_20.append(np.mean(np.abs((y_test - y_hat) / y_test)) * 100 if np.any(y_test != 0) else 0)
                r2_20.append(r2_score(y_test, y_hat))
            else:
                continue

        if mse_20:
            mae_total.append(mean(mae_20) * norm_param)
            mse_total.append(mean(mse_20) * (norm_param ** 2))
            mse_list.append(predictors)
            rmse_list.append(mean(rmse_20))
            mae_list.append(mean(mae_20))
            mape_list.append(mean(mape_20))
            r2_list.append(mean(r2_20))
        else:
            continue

    print("Mean Absolute Error: %.3f - Mean Squared Error: %.3f" % (mean(mae_total), mean(mse_total)))
    print("Minimum Mean Squared Error: %.3f" % (min(mse_total)))

    Y = mse_total
    X = mse_list

    Z = [x for _, x in sorted(zip(Y, X))]
    print(Z[0])
    print("Minimum Number of Features :", len(Z[0]))
    Z_temp = Z[:10]

    arr_num = [0] * 12

    for item in Z_temp:
        if 'var_1' in item:
            arr_num[0] = arr_num[0] + 1;
        if 'var_2' in item:
            arr_num[1] = arr_num[1] + 1;
        if 'var_3' in item:
            arr_num[2] = arr_num[2] + 1;
        if 'var_4' in item:
            arr_num[3] = arr_num[3] + 1;
        if 'var_5' in item:
            arr_num[4] = arr_num[4] + 1;
        if 'var_6' in item:
            arr_num[5] = arr_num[5] + 1;
        if 'var_7' in item:
            arr_num[6] = arr_num[6] + 1;
        if 'var_8' in item:
            arr_num[7] = arr_num[7] + 1;
        if 'var_9' in item:
            arr_num[8] = arr_num[8] + 1;
        if 'var_10' in item:
            arr_num[9] = arr_num[9] + 1;
        if 'var_11' in item:
            arr_num[10] = arr_num[10] + 1;
        if 'var_12' in item:
            arr_num[11] = arr_num[11] + 1;

    print(arr_num)
print("Average RMSE: %.3f" % mean(rmse_list))
print("Minimum RMSE: %.3f" % min(rmse_list))
print("MAE: %.3f" % mean(mae_list))
print("MAPE: %.3f" % mean(mape_list))
print("R^2 Score: %.3f" % mean(r2_list))
print("No. Features: %d" % len(mse_list[0]))`

**Comment by gaosir123** [comment]
I read the article you provided, and now I want to ask if this code is correct. I feel that the output value is still abnormal.
[新建文本文档 (2).txt](https://github.com/TomStog/Infrared-SpO2/files/14716387/2.txt)

**Comment by TomStog** [comment]
In line 76, you initialize mse_20 = [] twice. The second initialization is unnecessary.

In line 172, the number of features is fixed and is not equal to "len(mse_list[0])"

Also, be careful with your Tabs at the last prints

**Comment by gaosir123** [comment]
This error occurs when there is a lot of data. How to solve this problem?
Mean Absolute Error: nan - Mean Squared Error: nan
Traceback (most recent call last):
  File "D:/虚拟环境/实验大全/1.py", line 127, in <module>
    print("Minimum Mean Squared Error: %.3f" % (min(mse_total)))
ValueError: min() arg is an empty sequence
[9987.txt](https://github.com/TomStog/Infrared-SpO2/files/14734978/9987.txt)

**Comment by TomStog** [comment]
1) With my dataset, the code runs without errors. Maybe something is the matter with your dataset. But if "mse_total" is an empty list, it should have thrown an error just one line above with "mean(mse_total)".

2) Another thing that i noticed is that even if it has run with no errors, the printed values are not correct, in terms of magnitude i mean. That's because you haven't take into consideration the norm_param. Let me give you an example from one of my runs :

Mean Absolute Error: 1.206 - Mean Squared Error: 2.443
Minimum Mean Squared Error: 2.193
('var_2', 'var_3', 'var_4', 'var_8', 'var_10')
Minimum Number of Features : 5
[0, 9, 1, 10, 0, 3, 5, 8, 1, 9, 2, 2]
Average RMSE: 0.016
Minimum RMSE: 0.015
MAE: 0.012
MAPE: 1.242
R^2 Score: 0.026

As you can see, the second time the Mean Absolute Error is printed, it's x100 smaller because norm_param isn't taken into consideration. Same goes for RMSE.

**Comment by gaosir123** [comment]
I adjusted this line of code and the value can be output after adjustment. What is the impact of this on the result?

if (all(x <= ((8 / norm_param) ** 2) for x in mse)):

Mean Absolute Error: 1.762 - Mean Squared Error: 6.007
Minimum Mean Squared Error: 5.897
('var_2', 'var_4', 'var_6', 'var_7', 'var_8', 'var_12')
Minimum Number of Features : 6
[0, 7, 5, 8, 0, 5, 6, 5, 0, 6, 6, 3]
Average RMSE: 0.025
Minimum RMSE: 0.024
MAE: 0.018
MAPE: 1.851
R^2 Score: -3.052

进程已结束,退出代码0

**Comment by TomStog** [comment]
You basically changed the acceptable Mean Squared Error threshold. By doing that, you lower the precision of your system. Without knowing what your dataset contains, I can't be much of assistance.

**Comment by gaosir123** [comment]
If this line of code is not modified, if the result can be output, does it mean that the model meets the accuracy standard?

**Comment by TomStog** [comment]
If this line of code is not modified and Mean Squared Error is less than 4 (or equivalently Root Mean Squared Error is less than 2) then the model meets the accuracy standards.

**Comment by gaosir123** [comment]
Mean Absolute Error: 1.304 - Mean Squared Error: 2.556
Minimum Mean Squared Error: 2.503
('var_3', 'var_4', 'var_5', 'var_6', 'var_8', 'var_9', 'var_10', 'var_11')
Minimum Number of Features : 8
[7, 3, 4, 10, 10, 10, 3, 10, 9, 9, 10, 9]
Average RMSE: 0.016
Minimum RMSE: 0.016
MAE: 0.013
MAPE: 1.343
R^2 Score: -0.005

This is the result of running the Ridge regressor using your data. Most of the data gets the same result, but there are still some values ​​that are different. Please take a look at the reason.

[9987.txt](https://github.com/TomStog/Infrared-SpO2/files/14737992/9987.txt)

**Comment by gaosir123** [comment]
In addition, you used 6 input files during feature extraction, which I don't understand. My data was only collected under natural light, so I adjusted it to 3 inputs. I wonder if this caused the output problem.

**Comment by gaosir123** [comment]
This is part of the data obtained after current processing.
![1711333887554](https://github.com/TomStog/Infrared-SpO2/assets/153481043/4927d202-77f1-48ee-80bd-ad88774f56a3)

**Comment by TomStog** [comment]
1) The reason you get different metric values is because you don't normalize.
2) If you watch closely, I don't use 6 inputs, I also use 3 inputs.
3) Try to divide features [var_1, var_2, var_5, var_6, var_9, var_10] by 10 or try to multiply features [var_3, var_4, var_7, var_8, var_11, var_12] by 10.

**Comment by gaosir123** [comment]
A piece of code in the feature extraction code is like this, because you only provided the following three files, so what are the other three files? Isn't it six inputs?

mypath1 = '..\Forehead_Att\Forehead\Day1\03\';
info1 = dir(mypath1);

mypath2 = '..\Forehead_Amp\Forehead\Day1\03\';
info2 = dir(mypath2);

mypath3 = '..\Left_Cheek_Att\Left_Cheek\Day1\03\';
info3 = dir(mypath3);

mypath4 = '..\Left_Cheek_Amp\Left_Cheek\Day1\03\';
info4 = dir(mypath4);

mypath5 = '..\Right_Cheek_Att\Right_Cheek\Day1\03\';
info5 = dir(mypath5);

mypath6 = '..\Right_Cheek_Amp\Right_Cheek\Day1\03\';
info6 = dir(mypath6);

mapath2, 4, 6 exist but what are the others?

**Comment by TomStog** [comment]
These path directories are just some code leftovers, they are not used for feature extraction. I was experimenting on something and I just didn't remove that part. But I made sure not to raise any errors.You can check this yourself in lines 25, 76, 87.

**Comment by gaosir123** [comment]
Hello, now I use an ordinary camera to shoot faces under natural light, and then use your method to get the MSE that is not very ideal. Can you give me some advice?

**Comment by gaosir123** [comment]
For example, do I need to do anything else?

**Comment by TomStog** [comment]
1) Can you sent me your .xlsx file to try some things ?

2) Make sure the face in evenly lighted, shoot from a distance that doesn't add distortion/noise to your signal and include as many people as you can.

**Comment by gaosir123** [comment]
[1.csv](https://github.com/TomStog/Infrared-SpO2/files/14811800/1.csv)

**Comment by gaosir123** [comment]
This is almost half of my data.

**Comment by TomStog** [comment]
There are two instances of SpO2 being as low as 44 and 45 (line 31 and 32 from the .csv file). That's unimaginably low. I replaced this values with 94 and 95 and my best models met the accuracy standards. You should check the rest of your dataset for low SpO2 values.

**Comment by gaosir123** [comment]
With your help, I deleted rows 31 and 32, and the model meets the accuracy requirements, but my R2 score is negative, although I know there can be negative values. But because when I used your data set, only the R2 value was incorrect, and I also read the article you provided me, I thought there might still be a problem with the R2 calculation. Can you take a look at my code regarding the calculation of the R2 score?

**Comment by gaosir123** [comment]
[1.txt](https://github.com/TomStog/Infrared-SpO2/files/14814040/1.txt)
This is my code.
Mean Absolute Error: 1.536 - Mean Squared Error: 3.486
Minimum Mean Squared Error: 3.205
('var_1', 'var_2', 'var_4')
Minimum Number of Features : 3
[3, 10, 4, 3, 2, 3, 0, 5, 9, 0, 3, 2]
Average RMSE: 0.019
Minimum RMSE: 0.018
MAE: 0.015
MAPE: 1.587
R^2 Score: -0.017

This is my output.

**Comment by TomStog** [comment]
the calculation of the R2 score is correct.

**Comment by gaosir123** [comment]
At present, I noticed that in the code I output, the Average RMSE and Minimum RMSE are always around 0.018. I don’t know why this happens. This value does not change when I change the model.
Below is my output.

Mean Absolute Error: 1.409 - Mean Squared Error: 3.157
Minimum Mean Squared Error: 2.935
('var_2', 'var_6', 'var_7', 'var_8')
Minimum Number of Features : 4
[4, 9, 2, 1, 2, 9, 7, 10, 6, 1, 2, 1]
Average RMSE: 0.018
Minimum RMSE: 0.017
MAE: 0.014
MAPE: 1.468
R^2 Score: -0.042

**Comment by TomStog** [comment]
print("Average RMSE: %.3f" % mean(rmse_list)*norm_param)
print("Minimum RMSE: %.3f" % min(rmse_list)*norm_param)
print("MAE: %.3f" % mean(mae_list)*norm_param)

**Comment by gaosir123** [comment]
I have almost finished running these regressors, but why are the results very similar, with almost only a 0.001 difference? Is this normal? For example, the following is the output of one of the models.

Mean Absolute Error: 1.410 - Mean Squared Error: 3.159
Minimum Mean Squared Error: 2.952
('var_2', 'var_5', 'var_6', 'var_7', 'var_8')
Minimum Number of Features : 5
[4, 10, 0, 3, 4, 9, 8, 10, 4, 1, 3, 1]
Average RMSE: 1.777
Minimum RMSE: 1.718
MAE: 1.410
MAPE: 1.468
R^2 Score: -0.041

**Comment by TomStog** [comment]
I don't know, maybe it's due to the lack of data.

**Comment by gaosir123** [comment]
When using EVM amplification, should I use motion amplification or color amplification?

**Comment by TomStog** [comment]
I'm not aware of the latter, I don't know how it works.

**Comment by gaosir123** [comment]
[放大.txt](https://github.com/TomStog/Infrared-SpO2/files/14976181/default.txt)
This is my enlargement code.

**Comment by gaosir123** [comment]
This line is me using the exm program you provided.
evm_bin = 'C:\\Users\\86136\\Desktop\\EVM_Matlab_bin-1.1-win64 (2)\\evm.exe
This line is the selected magnification type.
magType = 'color' # Magnification type (motion or color)

**Comment by TomStog** [comment]
I haven't provided any evm program or code.

**Comment by gaosir123** [comment]
Yes, this is the EVM program obtained in that link.

**Comment by gaosir123** [comment]
And I got this code myself.

**Comment by TomStog** [comment]
And your question is what would be better to use: motion or color ?
In my own magnification code, I used motion.

**Comment by gaosir123** [comment]
Is there an architecture diagram of the ViViT model?

**Comment by TomStog** [comment]
Unfortunately, there isn't.

**Comment by gaosir123** [comment]
What are the objective functions and loss functions used in the machine learning model you use?

**Comment by TomStog** [comment]
The loss function (stated in line 86) is Mean Squared Error loss fuction. What do you mean by "objective functions" ?

**Comment by gaosir123** [comment]
Please tell me how you adjust the parameters when using Euler video amplification. For example, I saw in the article that the amplification frequency is between 0.4 and 4. Are there any other parameter adjustments?

**Comment by TomStog** [comment]
Also, the amplification factor is 120.

**Comment by gaosir123** [comment]
The magnification is set to 120, is there a reason?

**Comment by TomStog** [comment]
No particular reason, it was arbitrarily selected.

**Comment by gaosir123** [comment]
Are there any other parameter settings besides amplification factor and amplification frequency?

**Comment by TomStog** [comment]
level = 4
chromAttenuation = 1

**Comment by gaosir123** [comment]
Are these two parameters also set casually? Is there a reason?

**Comment by TomStog** [comment]
Yes, they are set manually, arbitrarily selected as well.

**Comment by gaosir123** [comment]
What is the setting of this level? What is the difference between it and magnification?

**Comment by gaosir123** [comment]
Level, what does it do?

**Comment by gaosir123** [comment]
Also, the reason why the amplification frequency range of 0.4-4 Hz is set is related to the human heart rate range. Isn’t it measuring blood oxygen saturation?

**Comment by TomStog** [comment]
For more information regarding these parameters and their impact, I suggest to read the origin paper "Eulerian Video Magnification for Revealing Subtle Changes in the World".

The reason we selected that frequency range was due to the hypothesis that Heart Rate and SpO2 share some common signal information. The results tend to agree.

**Comment by gaosir123** [comment]
Regarding features, can we further discuss the key features identified in the model from a clinical medicine perspective?

**Comment by TomStog** [comment]
You can contact me via LinkedIn

**Comment by gaosir123** [comment]
Sorry, I don’t have a LinkedIn account, so can I share it here?

**Comment by TomStog** [comment]
Anyway, I think it would be best to have a video call. Choose the platform and send me the invitation link.
